# Generated by Django 5.0.1 on 2024-10-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregistration',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
